spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true           # H2 콘솔 열기
      path: /h2-console       # http://localhost:10002/h2-console
  sql:
    init:
      mode: always    
  # datasource:
  #   username: postgres
  #   password: postgres
  #   url: jdbc:p6spy:postgresql://localhost:5432/nova
  #   driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  #   hikari:
  #     maximum-pool-size: 10
  #     minimum-idle: 512
  #     idle-timeout: 30000
  #     max-lifetime: 1800000
  #     connection-timeout: 30000
  # main:
  #   allow-bean-definition-overriding: true

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    # database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect
  modulith:
    detection-strategy: explicitly-annotated

management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 9090
  tomcat:
    accept-count: 1000
    max-connections: 50000
    threads:
      max: 1000
      min-spare: 50

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.p6spy: DEBUG
    p6spy: DEBUG
